<?php
namespace bedIQ;
/**
 * Class Post_Type_Offer
 */
class Post_Type_Offer extends Post_Type {
    /**
     * Constructor for Post_Type_Offer
     */
    function __construct() {
        add_action( 'init', array( $this, 'register_post_type' ) );
        add_action( 'init', array( $this, 'register_taxonomy' ) );
        $this->add_meta_box();
    }

    /**
     * Register post type
     *
     * @return void
     */
    public function register_post_type() {
        $show_in_menu = true;
        register_post_type( 'offer', array(
            'label'           => __( 'Offers', 'bediq' ),
            'public'          => true,
            'show_ui'         => true,
            'show_in_menu'    => $show_in_menu,
            'menu_position'   => 6,
            'capability_type' => 'post',
            'hierarchical'    => false,
            'rewrite'         => array('slug' => 'offers'),
            'query_var'       => true,
            'has_archive'     => true,
            'supports'        => array('title', 'editor', 'thumbnail'),
            'menu_icon'       => 'dashicons-tickets-alt',
            'taxonomies'      => [ 'hotel_offers' ],
            'labels'          => array(
                'name'               => __( 'Offers', 'bediq' ),
                'singular_name'      => __( 'Offer', 'bediq' ),
                'menu_name'          => __( 'Offers', 'bediq' ),
                'add_new'            => __( 'Add Offer', 'bediq' ),
                'add_new_item'       => __( 'Add New Offer', 'bediq' ),
                'edit'               => __( 'Edit', 'bediq' ),
                'edit_item'          => __( 'Edit Offer', 'bediq' ),
                'new_item'           => __( 'New Offer', 'bediq' ),
                'view'               => __( 'View Offer', 'bediq' ),
                'view_item'          => __( 'View Offer', 'bediq' ),
                'search_items'       => __( 'Search Offers', 'bediq' ),
                'not_found'          => __( 'No Offers Found', 'bediq' ),
                'not_found_in_trash' => __( 'No Offers Found in Trash', 'bediq' ),
                'parent'             => __( 'Parent Offer', 'bediq' ),
            ),
            'rewrite'          =>  array(
                'slug'               => 'offers',
                'with_front'         => true,
                'pages'              => true,
                'feeds'              => true,
            ),
        ) );
    }

    /**
     * Register taxonomy
     *
     * @return void
     */
    public function register_taxonomy() {
        register_taxonomy( 'offer_types', array( 'offer' ),
            array(
                'hierarchical'   => true,
                'label'          => __( 'Offer Types', 'bediq' ),
                'show_ui'        => true,
                'query_var'      => true,
                'rewrite'        => array('slug' => 'hotel-offers'),
                'singular_label' => __( 'Offers', 'bediq' )
            )
        );
    }

    /**
     * Add meta box
     */
    public function add_meta_box() {
        if ( function_exists('acf_add_local_field_group') ) {
            acf_add_local_field_group(array(
                'key' => 'group_5d0886c4c4bd0',
                'title' => 'Booking',
                'fields' => array(
                    array(
                        'key' => 'field_5d0886db10d80',
                        'label' => 'Booking URL',
                        'name' => 'bediq_offer_booking_url',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d08870610d81',
                        'label' => 'Offer Code',
                        'name' => 'bediq_offer_code',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'offer',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

            acf_add_local_field_group(array(
                'key' => 'group_5d08b3e862749',
                'title' => 'Downloads',
                'fields' => array(
                    array(
                        'key' => 'field_5d08b3f37d9fa',
                        'label' => '',
                        'name' => 'downloads',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 1,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add new download',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5d08b40f7d9fb',
                                'label' => 'Download Name',
                                'name' => 'download_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5d08b4297d9fc',
                                'label' => 'Upload File',
                                'name' => 'upload_file',
                                'type' => 'file',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'library' => 'all',
                                'min_size' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'offer',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

            acf_add_local_field_group(array(
                'key' => 'group_5d08b541a8fd8',
                'title' => 'Gallery Images',
                'fields' => array(
                    array(
                        'key' => 'field_5d08b54eddbfe',
                        'label' => '',
                        'name' => 'gallery_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'offer',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

            acf_add_local_field_group(array(
                'key' => 'group_5d08b262016ed',
                'title' => 'Offer Good For',
                'fields' => array(
                    array(
                        'key' => 'field_5d08b27996ab3',
                        'label' => '',
                        'name' => 'offer_good_for',
                        'type' => 'checkbox',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Family' => 'Family',
                            'Couple' => 'Couple',
                            'Friends' => 'Friends',
                            'Solo Traveller' => 'Solo Traveller',
                            'Corporate' => 'Corporate',
                        ),
                        'allow_custom' => 0,
                        'default_value' => array(
                        ),
                        'layout' => 'vertical',
                        'toggle' => 0,
                        'return_format' => 'value',
                        'save_custom' => 0,
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'offer',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

            acf_add_local_field_group(array(
                'key' => 'group_5d08b2d9caf32',
                'title' => 'Offer Type',
                'fields' => array(
                    array(
                        'key' => 'field_5d08b2e6fec77',
                        'label' => '',
                        'name' => 'offer_type',
                        'type' => 'checkbox',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Discount' => 'Discount',
                            'Value-Add' => 'Value-Add',
                            'Package' => 'Package',
                            'Flash Sale' => 'Flash Sale',
                        ),
                        'allow_custom' => 0,
                        'default_value' => array(
                        ),
                        'layout' => 'vertical',
                        'toggle' => 0,
                        'return_format' => 'value',
                        'save_custom' => 0,
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'offer',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

            acf_add_local_field_group(array(
                'key' => 'group_5d0216520406d',
                'title' => 'Offers',
                'fields' => array(
                    array(
                        'key' => 'field_5d02166562276',
                        'label' => 'Location Available',
                        'name' => 'location_available',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 1,
                        'max' => 0,
                        'layout' => 'row',
                        'button_label' => 'Add New Offer',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5d0217c862277',
                                'label' => '',
                                'name' => 'available_offer',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_5d02166562276',
                                            'operator' => '!=empty',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                ),
                                'default_value' => array(
                                ),
                                'allow_null' => 0,
                                'multiple' => 1,
                                'ui' => 1,
                                'ajax' => 1,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5d021994117ed',
                        'label' => 'Original Price',
                        'name' => 'original_price',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d0219ab117ee',
                        'label' => 'Offer Price',
                        'name' => 'offer_price',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d0219e0117ef',
                        'label' => 'Minimum Booking',
                        'name' => 'minimum_booking',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d021a41117f0',
                        'label' => 'Unit',
                        'name' => 'unit',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Amount' => 'Amount',
                            'People' => 'People',
                            'Night' => 'Night',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5d021a95117f1',
                        'label' => 'Advance Booking',
                        'name' => 'advance_booking',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_5d021ad1117f2',
                        'label' => 'Unit',
                        'name' => 'advance_booking_unit',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Hours' => 'Hours',
                            'Weeks' => 'Weeks',
                            'Days' => 'Days',
                            'Months' => 'Months',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5d0311d0276a9',
                        'label' => 'Visibility',
                        'name' => 'visibility',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 1,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Add new date range',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5d0311ec276aa',
                                'label' => '',
                                'name' => 'date_range',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d031247276ab',
                                        'label' => 'From',
                                        'name' => 'visibility_from_date',
                                        'type' => 'date_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'display_format' => 'd/m/Y',
                                        'return_format' => 'd/m/Y',
                                        'first_day' => 1,
                                    ),
                                    array(
                                        'key' => 'field_5d031278276ac',
                                        'label' => 'To',
                                        'name' => 'visibility_to_date',
                                        'type' => 'date_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'display_format' => 'd/m/Y',
                                        'return_format' => 'd/m/Y',
                                        'first_day' => 1,
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d0871934ed3a',
                                'label' => 'Days',
                                'name' => 'visiblity_days',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d0871b84ed3b',
                                        'label' => '',
                                        'name' => 'days',
                                        'type' => 'checkbox',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-visiblity-days',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'Monday' => 'Monday',
                                            'Tuesday' => 'Tuesday',
                                            'Wednesday' => 'Wednesday',
                                            'Thursday' => 'Thursday',
                                            'Friday' => 'Friday',
                                            'Saturday' => 'Saturday',
                                            'Sunday' => 'Sunday',
                                        ),
                                        'allow_custom' => 0,
                                        'default_value' => array(
                                        ),
                                        'layout' => 'vertical',
                                        'toggle' => 0,
                                        'return_format' => 'value',
                                        'save_custom' => 0,
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d0872b0e1e32',
                                'label' => 'From HH:mm',
                                'name' => 'start_time',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d0872fee1e33',
                                        'label' => '',
                                        'name' => 'monday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08732be1e34',
                                        'label' => '',
                                        'name' => 'tuesday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d087347e1e35',
                                        'label' => '',
                                        'name' => 'wednesday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08735be1e36',
                                        'label' => '',
                                        'name' => 'thursday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08736ee1e37',
                                        'label' => '',
                                        'name' => 'friday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08737fe1e38',
                                        'label' => '',
                                        'name' => 'saturday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d087396e1e39',
                                        'label' => '',
                                        'name' => 'sunday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d0873b1e1e3a',
                                'label' => 'To HH:mm',
                                'name' => 'end_time',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d0873c3e1e3b',
                                        'label' => '',
                                        'name' => 'monday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d0873dce1e3c',
                                        'label' => '',
                                        'name' => 'tuesday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d0873ebe1e3d',
                                        'label' => '',
                                        'name' => 'wednesday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d0873fae1e3e',
                                        'label' => '',
                                        'name' => 'thursday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d087405e1e3f',
                                        'label' => '',
                                        'name' => 'friday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d087410e1e40',
                                        'label' => '',
                                        'name' => 'saturday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08741de1e41',
                                        'label' => '',
                                        'name' => 'sunday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5d08841ba50e6',
                        'label' => 'Eligibility',
                        'name' => 'bediq_eligibility',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 1,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Add new date range',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5d08841ca50e7',
                                'label' => '',
                                'name' => 'date_range',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d08841ca50e8',
                                        'label' => 'From',
                                        'name' => 'visibility_from_date',
                                        'type' => 'date_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'display_format' => 'd/m/Y',
                                        'return_format' => 'd/m/Y',
                                        'first_day' => 1,
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50e9',
                                        'label' => 'To',
                                        'name' => 'visibility_to_date',
                                        'type' => 'date_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'display_format' => 'd/m/Y',
                                        'return_format' => 'd/m/Y',
                                        'first_day' => 1,
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d08841ca50ea',
                                'label' => 'Days',
                                'name' => 'visiblity_days',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d08841ca50eb',
                                        'label' => '',
                                        'name' => 'days',
                                        'type' => 'checkbox',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-visiblity-days',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'Monday' => 'Monday',
                                            'Tuesday' => 'Tuesday',
                                            'Wednesday' => 'Wednesday',
                                            'Thursday' => 'Thursday',
                                            'Friday' => 'Friday',
                                            'Saturday' => 'Saturday',
                                            'Sunday' => 'Sunday',
                                        ),
                                        'allow_custom' => 0,
                                        'save_custom' => 0,
                                        'default_value' => array(
                                        ),
                                        'layout' => 'vertical',
                                        'toggle' => 0,
                                        'return_format' => 'value',
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d08841ca50ec',
                                'label' => 'From HH:mm',
                                'name' => 'start_time',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d08841ca50ed',
                                        'label' => '',
                                        'name' => 'monday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50ee',
                                        'label' => '',
                                        'name' => 'tuesday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50ef',
                                        'label' => '',
                                        'name' => 'wednesday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50f0',
                                        'label' => '',
                                        'name' => 'thursday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50f1',
                                        'label' => '',
                                        'name' => 'friday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50f2',
                                        'label' => '',
                                        'name' => 'saturday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50f3',
                                        'label' => '',
                                        'name' => 'sunday_start',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d08841ca50f4',
                                'label' => 'To HH:mm',
                                'name' => 'end_time',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d08841ca50f5',
                                        'label' => '',
                                        'name' => 'monday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50f6',
                                        'label' => '',
                                        'name' => 'tuesday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50f7',
                                        'label' => '',
                                        'name' => 'wednesday_end',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50f8',
                                        'label' => '',
                                        'name' => 'thursday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50f9',
                                        'label' => '',
                                        'name' => 'friday_end',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50fa',
                                        'label' => '',
                                        'name' => 'saturday_end',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d08841ca50fb',
                                        'label' => '',
                                        'name' => 'sunday_end',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5d088536abcad',
                        'label' => 'Availability',
                        'name' => 'bediq_availability',
                        'type' => 'repeater',
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 1,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Add new date range',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5d088536abcae',
                                'label' => '',
                                'name' => 'date_range',
                                'type' => 'group',
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d088536abcaf',
                                        'label' => 'From',
                                        'name' => 'visibility_from_date',
                                        'type' => 'date_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'display_format' => 'd/m/Y',
                                        'return_format' => 'd/m/Y',
                                        'first_day' => 1,
                                    ),
                                    array(
                                        'key' => 'field_5d088536abcb0',
                                        'label' => 'To',
                                        'name' => 'visibility_to_date',
                                        'type' => 'date_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'display_format' => 'd/m/Y',
                                        'return_format' => 'd/m/Y',
                                        'first_day' => 1,
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d088536abcb1',
                                'label' => 'Days',
                                'name' => 'visiblity_days',
                                'type' => 'group',
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d088536abcb2',
                                        'label' => '',
                                        'name' => 'days',
                                        'type' => 'checkbox',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-visiblity-days',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'Monday' => 'Monday',
                                            'Tuesday' => 'Tuesday',
                                            'Wednesday' => 'Wednesday',
                                            'Thursday' => 'Thursday',
                                            'Friday' => 'Friday',
                                            'Saturday' => 'Saturday',
                                            'Sunday' => 'Sunday',
                                        ),
                                        'allow_custom' => 0,
                                        'save_custom' => 0,
                                        'default_value' => array(
                                        ),
                                        'layout' => 'vertical',
                                        'toggle' => 0,
                                        'return_format' => 'value',
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d088536abcb3',
                                'label' => 'From HH:mm',
                                'name' => 'start_time',
                                'type' => 'group',
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d088536abcb4',
                                        'label' => '',
                                        'name' => 'monday_start',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088536abcb5',
                                        'label' => '',
                                        'name' => 'tuesday_start',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088536abcb6',
                                        'label' => '',
                                        'name' => 'wednesday_start',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088536abcb7',
                                        'label' => '',
                                        'name' => 'thursday_start',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088536abcb8',
                                        'label' => '',
                                        'name' => 'friday_start',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088536abcb9',
                                        'label' => '',
                                        'name' => 'saturday_start',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088537abcba',
                                        'label' => '',
                                        'name' => 'sunday_start',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d088537abcbb',
                                'label' => 'To HH:mm',
                                'name' => 'end_time',
                                'type' => 'group',
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d088537abcbc',
                                        'label' => '',
                                        'name' => 'monday_end',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088537abcbd',
                                        'label' => '',
                                        'name' => 'tuesday_end',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088537abcbe',
                                        'label' => '',
                                        'name' => 'wednesday_end',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088537abcbf',
                                        'label' => '',
                                        'name' => 'thursday_end',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088537abcc0',
                                        'label' => '',
                                        'name' => 'friday_end',
                                        'type' => 'time_picker',
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088537abcc1',
                                        'label' => '',
                                        'name' => 'saturday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                    array(
                                        'key' => 'field_5d088537abcc2',
                                        'label' => '',
                                        'name' => 'sunday_end',
                                        'type' => 'time_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => 'bediq-time-picker',
                                            'id' => '',
                                        ),
                                        'display_format' => 'g:i a',
                                        'return_format' => 'g:i a',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5d0888ff4a970',
                        'label' => __( 'Conditions', 'bediq' ),
                        'name' => 'conditions',
                        'type' => 'repeater',
                        'min' => 1,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => __( 'Add new condtion', 'bediq' ),
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5d08891b4a971',
                                'label' => '',
                                'name' => 'condition',
                                'type' => 'text',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5d088951e3b8c',
                        'label' => __( 'Description', 'bediq' ),
                        'name' => 'description',
                        'type' => 'textarea',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'offer',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));

        }
    }
}